# Generated by Django 4.2.9 on 2024-01-09 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('game_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='GamePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('post_image_url', models.URLField()),
                ('link', models.URLField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('is_staff', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_posts', to='loopapi.game')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('platform_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('post_image_url', models.URLField()),
                ('link', models.URLField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('is_staff', models.BooleanField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_posts', to='loopapi.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_post_reactions', to='loopapi.platformpost')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_post_reactions', to='loopapi.reaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='platformpost',
            name='reactions',
            field=models.ManyToManyField(related_name='platform_posts', through='loopapi.PlatformPostReaction', to='loopapi.reaction'),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GamePostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_reactions', to='loopapi.gamepost')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_post_reactions', to='loopapi.reaction')),
            ],
        ),
        migrations.AddField(
            model_name='gamepost',
            name='reactions',
            field=models.ManyToManyField(related_name='game_posts', through='loopapi.GamePostReaction', to='loopapi.reaction'),
        ),
        migrations.AddField(
            model_name='gamepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='loopapi.platform'),
        ),
    ]
