# Generated by Django 4.2.9 on 2024-01-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loopapi', '0002_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='platformId',
            new_name='platform',
        ),
    ]
