# Generated by Django 4.2.9 on 2024-01-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loopapi', '0003_rename_platformid_game_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='platform_id',
            new_name='platform',
        ),
    ]
