# Generated by Django 4.2.9 on 2024-01-10 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loopapi', '0004_alter_game_game_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformpost',
            name='reactions',
        ),
        migrations.AddField(
            model_name='platformpost',
            name='likes',
            field=models.ManyToManyField(related_name='platform_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
    ]
