# Generated by Django 4.2.9 on 2024-01-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopapi', '0004_rename_game_id_post_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_staff',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
