# Generated by Django 4.2.9 on 2024-01-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loopapi', '0006_gamepost_platformpost_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_reactions', to='loopapi.platformpost')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_post_reactions', to='loopapi.reaction')),
            ],
        ),
        migrations.CreateModel(
            name='GamePostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_reactions', to='loopapi.gamepost')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_post_reactions', to='loopapi.reaction')),
            ],
        ),
        migrations.AddField(
            model_name='gamepost',
            name='reactions',
            field=models.ManyToManyField(related_name='game_posts', through='loopapi.GamePostReaction', to='loopapi.reaction'),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='reactions',
            field=models.ManyToManyField(related_name='platform_posts', through='loopapi.PlatformPostReaction', to='loopapi.reaction'),
        ),
    ]
