# Generated by Django 4.2.9 on 2024-01-08 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loopapi', '0007_platformpostreaction_gamepostreaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpostreaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='platform_post_reactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformpostreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_post_reactions', to='loopapi.platformpost'),
        ),
    ]
